- name: start kafka
  service: name=kafka state=started enabled=yes

- name: stop kafka
  service: name=kafka state=stopped enabled=yes

- name: restart kafka
  service: name=kafka state=restarted enabled=yes
