---
- hosts: kafka-nodes
  vars:
    zookeeper_user: "zookeeper"
    zookeeper_group: "zookeeper"
    zookeeper_url: "http://apache.uib.no/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz"
    archived_file: "zookeeper-3.4.14.tar.gz"
    zookeeper_version: zookeeper-3.4.14
    landing_zone: "/opt"
    zookeeper_home: "{{ landing_zone }}/{{ zookeeper_version }}"

  tasks:

  #  - name: Copy private key
  #    copy:
  #      src: "/home/centos/.ssh/id_rsa"
  #      dest: "/home/centos/.ssh/id_rsa"

    - name: Install packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - java-1.8.0-openjdk
        - nc
      become: yes

    - name: "Create group {{ zookeeper_group }}"
      group:
        name: "{{ zookeeper_group }}"
        state: present
      become: yes

    - name: "Add user {{ zookeeper_user }} with a bash shell, add to group {{ zookeeper_group }}"
      user:
        name: "{{ zookeeper_user }}"
        shell: /bin/bash
        group: "{{ zookeeper_group }}"
      become: yes

    - name: "Download {{ zookeeper_url }} to {{ landing_zone }}"
      get_url:
        url: "{{ zookeeper_url }}"
        dest: "{{ landing_zone }}"
      become: yes

    - name: "Extract {{ archived_file }} to {{ landing_zone }}"
      unarchive:
        src: "{{ landing_zone }}/{{ archived_file }}"
        dest: "{{ landing_zone }}"
        remote_src: yes
      become: yes

    - name: Create a directory data
      file:
        path: "{{ zookeeper_home }}/data"
        state: directory
        mode: '0755'
      become: yes

    - name: Change ownership
      file:
        path: "{{ landing_zone }}/{{ zookeeper_version }}"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
        recurse: yes
      become: yes

    - name: "Delete archive {{ landing_zone }}/{{ archived_file }}"
      file:
        path: "{{ landing_zone }}/{{ archived_file }}"
        state: absent
      become: yes

    - name: Copy zoo.cfg
      copy:
        src: "{{ local_workdir }}/zoo.cfg"
        dest: "{{ zookeeper_home }}/conf/zoo.cfg"
        owner: "{{ zookeeper_user }}"
        group: "{{ zookeeper_group }}"
      become: yes
      become_user: zookeeper

- hosts: localhost
  tasks:

    - name: Create myid files
      command: sh -c "echo '{{ index+1 }}' | ssh -i /home/centos/.ssh/id_rsa centos@{{ item }} -T 'cat > /home/centos/myid && sudo mv /home/centos/myid /opt/zookeeper-3.4.14/data && sudo chown zookeeper:zookeeper /opt/zookeeper-3.4.14/data/myid'"
      loop: "{{ groups['public-ips'] }}"
      loop_control:
        index_var: index

    - name: Generate /etc/ssh/ RSA host key pair
      command : "ssh-keygen -q -t rsa -f /tmp/id_rsa -C '' -N ''"
      args:
        creates: /tmp/id_rsa

- hosts: kafka-nodes
  vars:
    zookeeper_version: zookeeper-3.4.14
    landing_zone: "/opt"
    zookeeper_home: "{{ landing_zone }}/{{ zookeeper_version }}"

  tasks:
  #  - name: Copy public key
  #    copy:
  #      src: "/tmp/id_rsa.pub"
  #      dest: "/home/centos/.ssh/authorized_keys"
  #      owner: centos
  #      group: centos
    - lineinfile:
        path: /home/centos/.ssh/authorized_keys
        insertafter: last
        line: "{{lookup('file', '/tmp/id_rsa.pub')}}"      

    - name: Copy private key
      copy:
        src: "/tmp/id_rsa"
        dest: "/home/centos/.ssh/id_rsa"
        owner: centos
        group: centos
        mode: '0600'

    - name: "Start Zookeeper"
      shell: "{{ zookeeper_home }}/bin/zkServer.sh start"
      args:
        chdir: "{{ zookeeper_home }}"
      become: yes
      become_user: zookeeper
